name: Deploy Static Website

on:
  push:
    branches:
      - main   # Change to 'master' if that’s your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Folder that contains your index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

